name: Create Linear Issue on Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: ["opened", "edited", "reopened", "synchronize"]

permissions:
  pull-requests: write

jobs:
  create-linear-issue-on-pull-request:
    runs-on: ubuntu-latest
    name: (JOB) Find or Create Linear Issue on Pull Request
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout action repo
        uses: actions/checkout@v3
      - name: (STEP) Find or Create the Linear Issue on Pull Request
        id: findOrCreateIssue
        uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: "CHR"
          linear-created-issue-title-prefix: "[GITHUB] " # Done
          linear-created-issue-state-id: "d8dc0111-0862-4ea9-8eb5-e7c127f847ce" # Done
          linear-issue-label-ids: "ea7fc863-71f7-409c-bcda-b42a22dc9a75,7c8d0d42-b53c-49c4-ba23-b48f6e14eb62,77c37057-9bd9-413b-a8b8-5aabd7c1a557"
      - name: Create comment in PR with Linear Issue link
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.findOrCreateIssue.outputs.linear-issue-url }}
